import { Skeleton } from "@/components/ui/skeleton";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { io } from "socket.io-client";
const socket = io("https://socket-serve.adaptable.app");

const Index: NextPage = () => {
  const router = useRouter();
  const [statusFromSocket, setStatusFromSocket] = useState<boolean>(false);
  const [status, setStatus] = useState<boolean>(false);
  const [localForm, setLocalForm] = useState<string>("");

  const onAction = () => {
    setStatus(!status);
    socket.emit("action", { status: !status });
  };

  useEffect(() => {
    socket.on("receive_action", (data) => {
      setStatusFromSocket(data.status);
      setStatus(data.status);
    });
  }, []);

  useEffect(() => {
    const getLocalForm = localStorage.getItem("socket.io");
    if (getLocalForm !== null) {
      setLocalForm(JSON.parse(getLocalForm!));
    } else {
      router.push("/input-user");
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>SOCKET.IO</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="flex flex-col items-center justify-center w-full h-screen mx-auto lg:w-1/2">
        <div className="mb-2 text-xl font-light tracking-wide uppercase">
          <>
            {localForm === "" ? (
              <Skeleton className="h-8 w-[200px]" />
            ) : (
              "Socket.IO"
            )}
          </>
        </div>
        <div className="text-4xl font-bold tracking-widest md:tracking-[0.2em] mb-7">
          {statusFromSocket ? (
            <>
              {localForm === "" ? (
                <Skeleton className="h-8 w-[340px]" />
              ) : (
                "Under Maintance"
              )}
            </>
          ) : (
            <>
              {localForm === "" ? (
                <Skeleton className="h-8 w-[340px]" />
              ) : (
                "Maintance Done"
              )}
            </>
          )}
        </div>
        {localForm === "" ? (
          <Skeleton className="h-10 w-[120px]" />
        ) : (
          <>
            {localForm === "admin" ? (
              <button
                className="px-4 py-2 text-sm uppercase rounded-md bg-slate-200 hover:bg-slate-100"
                onClick={onAction}
              >
                Set Maintance
              </button>
            ) : null}
          </>
        )}
      </div>
    </>
  );
};

export default Index;
