import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useCallback, useEffect, useState } from "react";
import OneSignal from "react-onesignal";

type Props = {};

const InputUser = (props: Props) => {
  const router = useRouter();
  const [username, setUsername] = useState<string>("");
  const [initialized, setInitialized] = useState(false);

  const onSubmit = useCallback(() => {
    localStorage.setItem("socket.io", JSON.stringify(username));
    router.push("/");
  }, [username, router]);

  useEffect(() => {
    OneSignal.init({
      appId: "bdca64d3-d4d8-4901-b757-814e07081223",
      safari_web_id: "web.onesignal.auto.32358c52-eb5f-4c9c-a5b8-d10e6e7ce454",
      notifyButton: {
        enable: true,
      },
    }).then(() => {
      setInitialized(true);
      OneSignal.showSlidedownPrompt().then(() => {
        // do other stuff
      });
    });
  }, []);

  return (
    <>
      <Head>
        <title>SOCKET.IO | Input User</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 h-screen mx-auto">
        <h1 className="mb-5 text-2xl font-bold">SOCKET.IO</h1>
        <AlertDialog>
          <AlertDialogTrigger asChild>
            <Button variant="outline">Input Username</Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
              <AlertDialogDescription>
                <div className="flex flex-col gap-2 my-3">
                  <Label>Username</Label>
                  <Input
                    type="text"
                    placeholder="Input username"
                    onChange={(e) => setUsername(e.target.value)}
                  />
                </div>
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={onSubmit}>Continue</AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </div>
    </>
  );
};

export default InputUser;
